# https://docs.github.com/ja/actions/creating-actions/metadata-syntax-for-github-actions

name: "Run Test Plan at Autify for Mobile"

description: >
  Run a Test Plan at Autify for Mobile on GitHub Actions

author: "Autify"

inputs:
  build_id:
    description: >
      Specify the ID of the Build you uploaded to Autify for Mobile. You can check it from the list of build files.
    required: true

  test_plan_id:
    description: >
      Specify the ID of the Test Plan you created with Autify for Mobile. You can check it in the URL. Example: `https://mobile-app.autify.com/projects/<Project ID>/test_plans/<Test Plan ID>`.
    required: true

outputs:
  test_result_id: # id of output
    value: ${{ steps.result.outputs.test_result_id }}

  error: # id of output
    value: ${{ steps.result.outputs.error }}

# runs:
#   using: "docker"
#   image: "Dockerfile"

runs:
  using: "composite"
  steps:
    - name: Run Test Plan
      shell: bash
      id: result
      run: >
        error () {
          echo "::error ::${1}"
          echo "::set-output title=error::${1}"
          exit 1
        }

        inputs_exist() {
          if echo "$1"  | grep -Eq '^[0-9]+$' ; then
            return 0
          fi
          return 1
        }

        main() {
          if ! inputs_exist "\${{ inputs.build }}"; then
            error "build_id should be specified"
          fi
        }

        main "$@"


    # - name: Run Test Plan
    #   shell: bash
    #   id: run_test_plan
    #   run: |
    #     echo ${{ inputs.build_id }}
    #     RUN_COMMAND="hello"
    #     echo "::set-output name=command::${RUN_COMMAND}"

branding:
  icon: "check-circle"
  color: "purple"
