# https://docs.github.com/ja/actions/creating-actions/metadata-syntax-for-github-actions

name: "Run Test Plan at Autify for Mobile"
description: Run a Test Plan at Autify for Mobile on GitHub Actions
author: "Autify"

inputs:
  build_id:
    description: >
      Specify the ID of the Build you uploaded to Autify for Mobile. You can check it from the list of build files.
    required: true

  test_plan_id:
    description: >
      Specify the ID of the Test Plan you created with Autify for Mobile. You can check it in the URL. Example: `https://mobile-app.autify.com/projects/<Project ID>/test_plans/<Test Plan ID>`.
    required: true

outputs:
  test_result_id: # id of the output
    description: "Hoge"
    value: ${{ steps.random-number-generator.outputs.test_result_id }}


runs:
  using: composite
  steps:
    - id: random-number-generator
      shell: bash
      run: >
        echo "Using Rainforest GitHub Action"
        echo "::set-output name=test_result_id::${A})"
      

branding:
  icon: "check-circle"
  color: "purple"
