# https://docs.github.com/ja/actions/creating-actions/metadata-syntax-for-github-actions

name: "Run Test Plan at Autify for Mobile"

description: >
  Run a Test Plan at Autify for Mobile on GitHub Actions

author: "Autify"

inputs:
  build_id:
    description: >
      Specify the ID of the Build you uploaded to Autify for Mobile. You can check it from the list of build files.
    required: true

  test_plan_id:
    description: >
      Specify the ID of the Test Plan you created with Autify for Mobile. You can check it in the URL. Example: `https://mobile-app.autify.com/projects/<Project ID>/test_plans/<Test Plan ID>`.
    required: true

outputs:
  command: # id of output
    description: 'The time we greeted you'
    value: ${{ steps.hoge.outputs.command }}

# runs:
#   using: "docker"
#   image: "Dockerfile"

runs:
  using: "composite"
  steps:
    - name: Hoge
      shell: bash
      id: hoge
      run: |
        RUN_COMMAND=1
        echo "::set-output name=command::${RUN_COMMAND}"

branding:
  icon: "check-circle"
  color: "purple"
