name: example-upload-build

on: [push]

jobs:
  autify-for-mobile:
    runs-on: ubuntu-latest
    steps:
      #
      # 1. Upload build
      #
      - name: Uploading a build
        uses: autifyhq/mobile-upload-build-action@main
        env:
          AUTIFY_FOR_MOBILE_API_TOKEN: ${{ secrets.AUTIFY_FOR_MOBILE_API_TOKEN }}
          AUTIFY_FOR_MOBILE_PROJECT_ID: ${{ secrets.PROJECT_ID }}

      #
      # 2. Run Test Plan with the build
      #
      - name: Funtional test
        uses: autifyhq/mobile-run-test-plan-action@main
        env:
          AUTIFY_FOR_MOBILE_API_TOKEN: ${{ secrets.AUTIFY_FOR_MOBILE_API_TOKEN }}
          # Use the build ID GitHub Actions uploaded in the previous step (1).
          AUTIFY_FOR_MOBILE_BUILD_ID: ${{ secrets.BUILD_ID }}
          AUTIFY_FOR_MOBILE_TEST_PLAN_ID: ${{ secrets.TEST_PLAN_ID }}